### ISSUE TITLE
More parsable format

### ISSUE THREAD

**Issue by kitagry** [hirosassa/bqvalid#4]
I think parsable error format is important  to use some useful tools ex) [reviewdog](https://github.com/reviewdog/reviewdog)
For example,

```
$ golint
comment_iowriter.go:11:6: exported type CommentWriter should have comment or be unexported
```

I want some option which change error format, or default format should be changed.
If you like this idea, I'll create PR.

**Comment by hirosassa** [comment]
@kitagry 
Thanks for your suggestion!
I agree with you. 

> default format should be changed

I prefer this idea.


> If you like this idea, I'll create PR

Yeah, go ahead👍
